name: measurements
description: A dart package providing basic classes for working with measurements such as Length and Mass.
version: 0.0.1
homepage: https://github.com/marcus-bornman/measurements

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.11.0